name: pulsenote_pro
description: "PulseNote Pro – metronome, setlist and note generator for musicians."
publish_to: 'none'

version: 1.0.2+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  flutter_soloud: ^3.2.1
  path_provider: ^2.0.15

dev_dependencies:
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/PN_android_icon.png
  min_sdk_android: 24
  adaptive_icon_background: "#009688"
  adaptive_icon_foreground: "assets/icon/PN_android_icon.png"

flutter_native_splash:
  color: "#0B0A13"
  color_dark: "#0B0A13"
  image: assets/icon/PN_android_icon.png
  android: true
  ios: true
  fullscreen: true
  android_gravity: center
  android_12:
    color: "#0B0A13"
    color_dark: "#0B0A13"
    image: assets/icon/PN_android_icon.png
    icon_background_color: "#0B0A13"
    icon_background_color_dark: "#0B0A13"